name: Create Package
description: create package on the private pypi repository
runs:
  using: "composite"
  steps:

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
          version: "0.5.1"

    - name: Install the project
      run: make dev-sync
      shell: bash

    - name: code validation
      run: make all-validation
      shell: bash

    - name: build package and publish
      run: make build-publish
      shell: bash
